import java.awt.event.KeyEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yca
 */
public class rapo44 extends javax.swing.JFrame {
   
    public  Connection c;
 public Statement st;
public  ResultSet rs;
    /**
     * Creates new form rapo44
     */
    public rapo44() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
         jTable1.setShowGrid(true);
          //jScrollPane1jScrollPane1.setHorizontalScrollBar(100);
         this.liste1();
         this.liste2();
         this.liste3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DETAYLI LİSTE");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "FORM NO", "ÜRÜN ADI", "MİN", "MAX", "GERÇEKLEŞEN", "TEST KOŞULLARI", "SAP", "FİRMA", "LOT NO", "TARİH", "SİPARİŞ NO", "GELEN MİKTAR", "ÜRÜN TÜRÜ", "KARAR", "SERTİFİKA", "NOTLAR", "FİRMA KOD", "FATURA NO", "BÖLÜMLER", "ŞARTLI KABUL", "RED", "KABUL", "Birim", "İRSALİYE NO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel1.setText("Sap");

        jLabel2.setText("Lot No");

        jLabel3.setText("Ürün Adı");

        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SİPARİŞ NO", "GELEN MİKTAR", "MİN", "MAX", "GERÇEKLEŞEN", "TEST KOŞUL", "FİRMA", "ÜRÜN TÜRÜ", "BÖLÜMLER", "KARAR", "SERTİFİKA", "S.K.FORM NO", "İRSALİYE NO" }));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox2, 0, 139, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2)
                    .addComponent(jComboBox3, 0, 139, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3)
                    .addComponent(jComboBox4, 0, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jComboBox1, 0, 134, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.ara();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        
                                       try{
               String combo3 =jComboBox2.getSelectedItem().toString();
       
        if (combo3.equals(null))
        {
            
        }
        else
        {
        jTextField1.setText(combo3);
        } 
          }   
          catch(Exception e)
                  {
                      
                  }
        
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        
                                       try{
               String combo3 =jComboBox3.getSelectedItem().toString();
       
        if (combo3.equals(null))
        {
            
        }
        else
        {
        jTextField2.setText(combo3);
        } 
          }   
          catch(Exception e)
                  {
                      
                  }
        
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
                                       try{
               String combo3 =jComboBox4.getSelectedItem().toString();
       
        if (combo3.equals(null))
        {
            
        }
        else
        {
        jTextField3.setText(combo3);
        } 
          }   
          catch(Exception e)
                  {
                      
                  }
        
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rapo44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rapo44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rapo44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rapo44.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rapo44().setVisible(true);
            }
        });
    }

         public void ara()
    {
        
        
        String ara1 = jComboBox1.getSelectedItem().toString(); 
         String ara2="";
         String ara3 = jTextField4.getText();
           if(ara1.equals("SİPARİŞ NO"))
           {
           ara2 ="sipno";
           }
          if(ara1.equals("GELEN MİKTAR"))
           {
           ara2 ="gelenmik";
           }
          if(ara1.equals("MİN"))
           {
           ara2 ="min";
           }
           if(ara1.equals("MAX"))
           {
           ara2 ="max";
           }      
           if(ara1.equals("GERÇEKLEŞEN"))
           {
           ara2 ="deger";
           }              
        if(ara1.equals("TEST KOŞUL"))
           {
           ara2 ="testkosul";
           }            
        if(ara1.equals("FİRMA"))
           {
           ara2 ="firma";
           }            
            if(ara1.equals("ÜRÜN TÜRÜ"))
           {
           ara2 ="urunturu";
           }                    
          if(ara1.equals("BÖLÜMLER"))
           {
           ara2 ="maltan";
           }                    
           if(ara1.equals("KARAR"))
           {
           ara2 ="karar";
           }
       if(ara1.equals("SERTİFİKA"))
           {
           ara2 ="sertifika";
           }
            if(ara1.equals("S.K.FORM NO"))
           {
           ara2 ="formno";
           }         
     //İRSALİYE NO
                        if(ara1.equals("İRSALİYE NO"))
           {
           ara2 ="irsaliyeno";
           }    
        
    
        DefaultTableModel tablo = (DefaultTableModel) jTable1.getModel();         
        int rows = tablo.getRowCount(); 
        for(int i = rows - 1; i >=0; i--)
        {
           tablo.removeRow(i); 
        }
   
        String sapara = jTextField1.getText();
        String lotara = jTextField2.getText();
        String urunara = jTextField3.getText();
    
        

  
   try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
             String query = "SELECT * FROM urun2 where urunadi like '%"+ urunara +"%' and sap like '%"+ sapara +"%' and lotno like '%"+ lotara +"%' and "+ ara2 +" like '%"+ ara3 +"%'";
      
        rs = st.executeQuery(query);
       
               while(rs.next())
         {
             
            String id  = rs.getString("id"); 
            String urunadi  = rs.getString("urunadi"); 
            String min  = rs.getString("min"); 
            String max  = rs.getString("max"); 
            String deger  = rs.getString("deger"); 
            String testkosul  = rs.getString("testkosul"); 
            String sap  = rs.getString("sap"); 
            String firma  = rs.getString("firma"); 
            String lotno  = rs.getString("lotno"); 
            String tarih  = rs.getString("tarih"); 
            String sipno  = rs.getString("sipno"); 
            String gelenmik  = rs.getString("gelenmik") + " " + rs.getString("ek4"); 
            String urunturu  = rs.getString("urunturu"); 
            String karar  = rs.getString("karar"); 
            String sertifika  = rs.getString("sertifika"); 
            String notlar  = rs.getString("notlar"); 
            String firmakod  = rs.getString("firmakod"); 
            String fatno  = rs.getString("fatno"); 
            String maltan  = rs.getString("maltan"); 
            String ek1  = rs.getString("ek1"); 
            String ek2  = rs.getString("ek2"); 
            String ek3  = rs.getString("ek3"); 
            String ek4  = rs.getString("ek4"); 
            String id2  = rs.getString("id2"); 
            String formno  = rs.getString("formno"); 
            String  irsaliyeno  = rs.getString("irsaliyeno"); 

           
          //yarım bıraktın devam et.
        tablo.addRow(new Object[] {id , formno , urunadi , min , max , deger , testkosul , sap , firma , lotno , tarih , sipno , gelenmik , urunturu , karar , sertifika , notlar , firmakod , fatno , maltan , ek1 , ek2 , ek3 , ek4  ,  irsaliyeno  });

         
         }


       }
       catch ( Exception e ) {
      System.err.println( e.getClass().getName() + ": " + e.getMessage() );
      System.exit(0);
    }
            
    } 
    
         
         
         
           public void liste1()
         {
             jComboBox2.addItem("");
              try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
               //String query = "SELECT * FROM urun where sap like '"+ arama +"' limit 1";
            
             String query = "SELECT DISTINCT sap FROM urun2" ;
      
        rs = st.executeQuery(query);
       
               while(rs.next())
         {

            String firma  = rs.getString("sap"); 
            
            //String firmakod  = rs.getString("firmakod"); 
            jComboBox2.addItem(firma);
  
         }


       }
       catch ( Exception e ) {
     // System.err.println( e.getClass().getName() + ": " + e.getMessage() );
    // JOptionPane.showMessageDialog(null , " Hatalı veya eksik giriş", "Hata", -1);
    }
         
         }  
    
           
           
           
                public void liste2()
         {
             jComboBox3.addItem("");
              try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
               //String query = "SELECT * FROM urun where sap like '"+ arama +"' limit 1";
            
             String query = "SELECT DISTINCT lotno FROM urun2" ;
      
        rs = st.executeQuery(query);
       
               while(rs.next())
         {

            String firma  = rs.getString("lotno"); 
            
            //String firmakod  = rs.getString("firmakod"); 
            jComboBox3.addItem(firma);
  
         }


       }
       catch ( Exception e ) {
     // System.err.println( e.getClass().getName() + ": " + e.getMessage() );
    // JOptionPane.showMessageDialog(null , " Hatalı veya eksik giriş", "Hata", -1);
    }
         
         }        
                
                
                
                    public void liste3()
         {
             jComboBox4.addItem("");
              try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
               //String query = "SELECT * FROM urun where sap like '"+ arama +"' limit 1";
            
             String query = "SELECT DISTINCT urunadi FROM urun2" ;
      
        rs = st.executeQuery(query);
       
               while(rs.next())
         {

            String firma  = rs.getString("urunadi"); 
            
            //String firmakod  = rs.getString("firmakod"); 
            jComboBox4.addItem(firma);
  
         }


       }
       catch ( Exception e ) {
     // System.err.println( e.getClass().getName() + ": " + e.getMessage() );
    // JOptionPane.showMessageDialog(null , " Hatalı veya eksik giriş", "Hata", -1);
    }
         
         }              
                
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
