/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author yca
 */
public class tedarik11 extends javax.swing.JFrame {
    public  Connection c;
 public Statement st;
public  ResultSet rs;
    /**
     * Creates new form rapor33
     */
    public tedarik11() {
        initComponents();
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
           jTable1.setAutoCreateRowSorter(true);
         jTable1.setShowGrid(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
                                   DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
	   //get current date time with Date()
	   Date date = new Date();
	
                   
           DateFormat dateFormat1 = new SimpleDateFormat("dd");
	   //get current date time with Date()
	   String gun = dateFormat1.format(date) ;
           
            DateFormat dateFormat2 = new SimpleDateFormat("MM");
	   //get current date time with Date()
	   String ay = dateFormat2.format(date) ;
                      
           DateFormat dateFormat3 = new SimpleDateFormat("yyyy");
	   //get current date time with Date()
	   String yil = dateFormat3.format(date) ;
           
          jTextField4.setText(yil);
          jTextField3.setText(ay);
          //jTextField1.setText(gun);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TEDARİKÇİ DEĞ.");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel1.setText("Gün");

        jLabel2.setText("Ay");

        jLabel3.setText("Yil");

        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Firma No", "FİRMA", "GELEN MİKTAR", "Kabul %", "Red Mik.", "%", "Ş.K. Mik.", "%", "Kabul Mik.", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(6).setMinWidth(15);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(8).setMinWidth(15);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(10).setMinWidth(15);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(50);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SİPARİŞ NO", "GELEN MİKTAR", "MİN", "MAX", "GERÇEKLEŞEN", "TEST KOŞUL", "FİRMA", "ÜRÜN TÜRÜ", "BÖLÜMLER", "KARAR", "SERTİFİKA", "S.K.FORM NO", "İRSALİYE NO" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.ara();
        
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
                        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
          this.ara();
        }  
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
            String combo2 =jComboBox1.getSelectedItem().toString();
        //jTextField6.setText(combo2);
             
            if (combo2.equals("FİRMA"))
            {
   try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
               //String query = "SELECT * FROM urun where sap like '"+ arama +"' limit 1";
            
             String query = "SELECT DISTINCT firma FROM urun" ;
      
        rs = st.executeQuery(query);
       
               while(rs.next())
         {

            String firma  = rs.getString("firma"); 
            
            //String firmakod  = rs.getString("firmakod"); 
            jComboBox2.addItem(firma);
  
         }


       }
       catch ( Exception e ) {
     // System.err.println( e.getClass().getName() + ": " + e.getMessage() );
    // JOptionPane.showMessageDialog(null , " Hatalı veya eksik giriş", "Hata", -1);
    }
  
            }
           else
            {
            jComboBox2.removeAllItems();
             jTextField5.setText("");
            }
               
            
            
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
          try{
               String combo2 =jComboBox2.getSelectedItem().toString();
        
        if (combo2.equals(null))
        {
            
        }
        else
        {
        jTextField5.setText(combo2);
        } 
          }   
          catch(Exception e)
                  {
                      
                  }
      
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rapor33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rapor33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rapor33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rapor33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rapor33().setVisible(true);
            }
        });
    }
    
             public void ara()
    {
         String ara1 = jComboBox1.getSelectedItem().toString(); 
         String ara2="";
         String ara3 = jTextField5.getText();
           if(ara1.equals("SİPARİŞ NO"))
           {
           ara2 ="sipno";
           }
          if(ara1.equals("GELEN MİKTAR"))
           {
           ara2 ="gelenmik";
           }
          if(ara1.equals("MİN"))
           {
           ara2 ="min";
           }
           if(ara1.equals("MAX"))
           {
           ara2 ="max";
           }      
           if(ara1.equals("GERÇEKLEŞEN"))
           {
           ara2 ="deger";
           }              
        if(ara1.equals("TEST KOŞUL"))
           {
           ara2 ="testkosul";
           }            
        if(ara1.equals("FİRMA"))
           {
           ara2 ="firma";
           }            
            if(ara1.equals("ÜRÜN TÜRÜ"))
           {
           ara2 ="urunturu";
           }                    
          if(ara1.equals("BÖLÜMLER"))
           {
           ara2 ="maltan";
           }                    
           if(ara1.equals("KARAR"))
           {
           ara2 ="karar";
           }
       if(ara1.equals("SERTİFİKA"))
           {
           ara2 ="sertifika";
           }
            if(ara1.equals("S.K.FORM NO"))
           {
           ara2 ="formno";
           }         
     //İRSALİYE NO
                        if(ara1.equals("İRSALİYE NO"))
           {
           ara2 ="irsaliyeno";
           }    
        
        
        
     
        DefaultTableModel tablo = (DefaultTableModel) jTable1.getModel();         
        int rows = tablo.getRowCount(); 
        for(int i = rows - 1; i >=0; i--)
        {
           tablo.removeRow(i); 
        }
   
        String t1 = jTextField1.getText();
        String t2 = jTextField3.getText();
        String t3 = jTextField4.getText();
    
      String tarih2 = t1 + "." + t2 + "." + t3;
      if (t2.equals(""))
      {
        tarih2 =  t3;
      }

  
   try {     
       
      int sk = 0;
      int red = 0 ;
       double kabul = 0;
       double yuzde =0;
        double yuzde2 =0;
         double yuzde3 =0;
      String firmayaz = "";
      String firmakodyaz = "";
       String firmakiyasla = "" ;
       
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
            st = c.createStatement();
            
             String query = "SELECT * FROM urun2 where tarih like '%"+ tarih2 +"%' and "+ ara2 +" like '%"+ ara3 +"%' ORDER BY firma ASC";
      
        rs = st.executeQuery(query);
 
               while(rs.next())
         {
             
            String id  = rs.getString("id"); 
            String urunadi = rs.getString("urunadi"); 
            String lotno = rs.getString("lotno"); 
            String tarih  = rs.getString("tarih"); 
            String sipno  = rs.getString("sipno"); 
            String gelenmik  = rs.getString("gelenmik") + " " + rs.getString("ek4") ; 
            String min = rs.getString("min"); 
            String  max  = rs.getString("max"); 
            String deger  = rs.getString("deger"); 
            String testkosul  = rs.getString("testkosul"); 
            String sap  = rs.getString("sap"); 
            String firma  = rs.getString("firma"); 
            String urunturu  = rs.getString("urunturu"); 
            String maltan  = rs.getString("maltan"); 
            String karar  = rs.getString("karar"); 
            String sertifika  = rs.getString("sertifika"); 
            String formno  = rs.getString("formno"); 
            String notlar  = rs.getString("notlar"); 
            String firmakod  = rs.getString("firmakod"); 
            String ek1  = rs.getString("ek1");
            String ek2 = rs.getString("ek2");
            String ek3 = rs.getString("ek3");
            
                        if(firmakiyasla.equals(""))
                        {
                         firmakiyasla = firma ; 
                        }
                        if(firmakiyasla.equals(firma))
                        {
                         
                        }
                        else
                        {
                            try
                            {
                                yuzde = 0;
                            yuzde = (kabul*100)/(sk+red+kabul);
                            }
                            catch(Exception e)
                              {
                              yuzde = 0;
                              }
                            
                               try
               {
                   yuzde2 = 0;
               yuzde2 = (red*100)/(sk+red+kabul);
               }
               catch(Exception e)
                 {
                 yuzde2 = 0;
                 }
                   
                try
               {
                   yuzde3 = 0;
               yuzde3 = (sk*100)/(sk+red+kabul);
               }
               catch(Exception e)
                 {
                 yuzde3 = 0;
                 } 
                            
                            
                             double toplamdeger = sk+red+kabul ;
              // tablo.addRow(new Object[] { "", "" , "" , "" ,"" , "" , "" , "" , "" , "" , "" , "" , "" , "" , "" , "" , "" , "Toplam : " + sk+red+kabul , sk  , red , kabul + " Kabul Yüzdesi : " + yuzde });
              // tablo.addRow(new Object[] { "", "" , "" , "" , "" ,"" , "" , "" , "Toplam : " + toplamdeger , "" ,"Kabul Yüzdesi : " + yuzde , "",   sk  , red , kabul });
                 
                                 if (toplamdeger > 0 )
              {
    tablo.addRow(new Object[] {  "", firmakodyaz , firmayaz  ,"Toplam : " + toplamdeger ,  yuzde , red  , yuzde2 , sk  ,  yuzde3 , kabul ,  yuzde  });       
              }

             
                   firmakiyasla = firma ; 
                        sk = 0;
                        red = 0 ;
                        kabul = 0;
                        }
            
            
            try
            {
            sk = sk + Integer.valueOf(ek1);

            }
            catch (Exception e)
            {
            }
            
                        try
            {
                 red = red + Integer.valueOf(ek2);
   
            }
            catch (Exception e)
            {
            }
                                    try
            {

            kabul = kabul + Integer.valueOf(ek3);
            }
            catch (Exception e)
            {
            }
            
       firmayaz = firma ;
      firmakodyaz = firmakod;
      
      
      
      
      
         
         }
   
             
               try
               {
                   yuzde = 0;
               yuzde = (kabul*100)/(sk+red+kabul);
               }
               catch(Exception e)
                 {
                 yuzde = 0;
                 }
               
                   try
               {
                   yuzde2 = 0;
               yuzde2 = (red*100)/(sk+red+kabul);
               }
               catch(Exception e)
                 {
                 yuzde2 = 0;
                 }
                   
                try
               {
                   yuzde3 = 0;
               yuzde3 = (sk*100)/(sk+red+kabul);
               }
               catch(Exception e)
                 {
                 yuzde3 = 0;
                 } 
                   
               
               
                double toplamdeger = sk+red+kabul ;
               
              if (toplamdeger > 0 )
              {
    tablo.addRow(new Object[] {  "", firmakodyaz , firmayaz  ,"Toplam : " + toplamdeger ,  yuzde , red  ,  yuzde2 , sk  ,  yuzde3 , kabul ,  yuzde  });                }

       }
       catch ( Exception e ) {
      System.err.println( e.getClass().getName() + ": " + e.getMessage() );
      System.exit(0);
    }
        
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
