import java.awt.FileDialog;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JFrame;

import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.LinkOption.NOFOLLOW_LINKS;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.COPY_ATTRIBUTES;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;

import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yca
 */
public class yukle1 extends javax.swing.JFrame {
      public  Connection c;
 public Statement st;
public  ResultSet rs;
public String tarih;
 public static String id;
 public static String lotno;

    JFrame frame = new JFrame ("");
 FileDialog file = new FileDialog(frame,"Open", FileDialog.LOAD);
 String yol;
 String yol2;
  Path copy_from_1 ;
  Path copy_to_1 ;

  
    public yukle1() {
        initComponents();
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        jLabel1.setText("Lot no : "+rapor1.lotno);
               
        // DateFormat dateFormat = new SimpleDateFormat("ddMMyyyy HHmmss");
         DateFormat dateFormat = new SimpleDateFormat("ddMM HHmmss");
	   //get current date time with Date()
	   Date date = new Date();
	   tarih = dateFormat.format(date);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DOSYA YÜKLE");
        setResizable(false);

        jLabel1.setText("jLabel1");

        jTextField1.setEditable(false);

        jButton1.setText("Belge");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Yükle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          file.show();
     
  String d = (file.getDirectory() + file.getFile());
  //System.out.print(d);
                  if ( d.equals("nullnull") )
                               {  
                                JOptionPane.showMessageDialog(null, "Dosya Seçilmedi.", "Hata", -1);
                                }
                else
                {
                       yol = (file.getDirectory() + file.getFile());
        yol2 =  file.getFile() ;
                      copy_from_1 = Paths.get(file.getDirectory(), file.getFile());
        jTextField1.setText(yol);
    
   
                }

                    
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String asd1 = jTextField1.getText();
                
               if ( asd1.isEmpty()  )
                               {  
                                JOptionPane.showMessageDialog(null, "Dosya Seçilmedi. ", "Hata", -1);
                                } 
                                  else
                                  {
        copy_to_1 = Paths.get("file", tarih + " " + copy_from_1.getFileName().toString());    
        
        
       
       
       
        
      
        
         String file1 = tarih + " " + copy_from_1.getFileName().toString() ;
        
   try {
      Files.copy(copy_from_1, copy_to_1, REPLACE_EXISTING, COPY_ATTRIBUTES, NOFOLLOW_LINKS);

    } catch (IOException e) {
      //System.err.println(e);
    }
                     try      
                     {
                                           String id2 = rapor1.id;
                                              Class.forName("org.sqlite.JDBC");
                                                           c = DriverManager.getConnection("jdbc:sqlite:kalite.sqlite");
                                                           st = c.createStatement();
                                                           
      String  query = "INSERT INTO dosya(file , id2 )VALUES( '"+ file1 +"','"+ id2 +"')";

                                                           PreparedStatement ps;
                                                           ps = c.prepareStatement(query);
                                                           ps.executeUpdate();

                                                           JOptionPane.showMessageDialog(null,  " Dosya Yüklendi ", "Dosya Yüklendi", -1);       
                                                           jTextField1.setText("");
                                                           
                                                           
                                          }
                    catch ( Exception e ) 
                                                    {
                                                    System.err.println( e.getClass().getName() + ": " + e.getMessage() );
                                                   JOptionPane.showMessageDialog(null , " Hatalı veya eksik giriş", "Hata", -1);
                                                    }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
 } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yukle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yukle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yukle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yukle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yukle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
